### ISSUE TITLE
headers missing from aarch64 cross-compiler

### ISSUE THREAD

**Issue by JCaporuscio** [wpilibsuite/aarch64-bionic-toolchain#9]
If you include a file that ultimately depends on asm/sigcontext.h, that header can't be found using the debian version of the aarch64 cross-compiler.

![image](https://user-images.githubusercontent.com/18466341/138533867-871001a1-b01c-4ba6-9072-9237c5eb610b.png)

If you manually navigate to the toolchain location the header is missing on a debian/ubuntu system.
On a windows system the file is present and the issue is not present during build.

The one include we had that was affected by this was for something we don't use anymore - so for the time being we've just removed it and it's not blocking.  Unknown if this affects other includes or files in the toolchain.

This issue did not occur before updating to latest gradlerio/native utils.  Not sure if the toolchain downloaded by the gradle task changed with native utils or something else changed.

**Comment by JCaporuscio** [comment]
This also affects the string type (on both windows and debian versions of the toolchain):

![image](https://user-images.githubusercontent.com/18466341/138534863-7f5760b1-111d-4b3b-8080-0423a9f40af3.png)
![image](https://user-images.githubusercontent.com/18466341/138535029-e5b52d97-c723-4ecf-9d0e-ddcf3aa1370a.png)

So multiple headers are affected.

**Comment by PeterJohnson** [comment]
Should be fixed in 2.1.0 release.
